### ISSUE TITLE
Unable to clear mailings

### ISSUE THREAD

**Issue by jamesarbrown** [soonick/poMMo#80] opened 2012-06-20 14:39 UTC
Hi Adrian,

Long time no speak. Hope all is ok with you.

Recently downloaded your latest branch, and somewhere down the way the first email I send it created a "Unable to Spawn mailer" even though the test in the config worked. Anyway I need to replicate that issue and come back to it.

My main problem was then that I could not clear the mail and attempt to send a new mail. No matter how many times I clicked cancel mail it did not work.

In the end I butchered status_cmd.php like this :-

```
    if ($_GET['cmd'] == 'restart' || $_GET['cmd'] == 'cancel')
    {
        Pommo_Mail_Ctl::spawn(Pommo::$_baseUrl.'ajax/mailings_send4.php?id='
                .$mailing['id'].'&code='.$mailing['code']);
    }
    break;
        Pommo_Mail_Ctl::spawn(Pommo::$_baseUrl.'ajax/mailings_send4.php?id='
                .$mailing['id'].'&code='.$mailing['code']);
 }
$json->success();
```

Ie brought the spawn statement outside of the IF statement.

Clicked "cancel mailing" that time and it did cancel.

I need to investigate further, but it maybe worth trying a fresh install and purposely causing a mailing to fail (bad smtp etc) and seeing if you cancel.

JB

**Comment by soonick** [comment] 2012-06-26 03:44
Hello James,

It's nice hearing from you again. I have been very busy lately (as always), but I will try to take a look at what is happening here.

Thanks,
Adrian

**Comment by soonick** [comment] 2012-09-02 23:01
Hello James,

Are you still having this issue? I tried to reproduce it but I couldn't, can you give me some instructions?

Thanks,
Adrian

**Comment by soonick** [comment] 2012-09-19 00:24
Hello James,

I am closing this ticket because I couldn't reproduce it. If you are still having the issue feel free to reopen it with instructions of how to reproduce.

Regards,
Adrian

**Closed as completed by soonick** 2012-09-19 00:24 UTC
Labels: Bug
