### ISSUE TITLE
renew logo and UI

### ISSUE THREAD

**Issue by ghost** [soonick/poMMo#54] opened 2011-11-10 14:25 UTC
Hey guys,

in the upcomping months (from 20th of january onwards) I'll hav some time to spend. As I use the older versions of pommo a lot, I'd love to support the project. 

I am webdesigner and developer from Cologne, Germany. My php is not too bad, but I think, that I won't be able to spend so much time in the code. :-) Instead, I would love to provide a new logo and UI to the project.

I'd love to begin just by providing a basic theme. Lateron, one could think about turning it all to some AJAX-driven super-wow-thing. :-)

Some references of some actual webdesigns (I did all the designs and some of the coding): www.make-it-move.de (I did most of the films in the showcase, too - might be helpful someday?), www.anonymizr.com (not functional yet, still in alpha...), www.sireenan.de, www.ullrichfinanz.de, www.friedhofsgaertnerei-habel.de, www.lebensfilm.de (a bit older), and some more...

Excuse my english and give me feedback, if I may participate. :-)

MV

**Comment by soonick** [comment] 2011-11-11 00:44
Hello Mavo,

Everyone that wants to contribute in any way to the project is always welcome. I think poMMo is theme-able so we could probably include your redesign as another theme to give the users the option to choose. I am not completely sure of how this work, but if you provide the design I will check it.

I will close this ticket because this is not a bug or a needed feature, but something nice to have. Anyway you are welcome to contribute and ask me any question you may have.

Regards,
Adrian Ancona

**Closed as completed by soonick** 2011-11-11 00:44 UTC
