### ISSUE TITLE
Mailing history page javascript error.

### ISSUE THREAD

**Issue by msd101psu** [soonick/poMMo#89] opened 2012-09-05 13:54 UTC
I got a colNames <> colModel javascript error on the mailings history page.  I removed the comma after the last colNames item on line 55 of themes\default\admin\mailings\mailings_hostory.php to eliminate the error.  Thanks.

**Comment by soonick** [comment] 2012-09-10 18:53
I am not getting that error.

Can you give us some more information so we can try to reproduce?
How many records did you have in the history table?
Which browser you were using?
What were you doing when you got the error?

Thanks,
Adrian

**Comment by soonick** [comment] 2012-09-19 00:23
Closing bug because of inability to reproduce.

**Closed as completed by soonick** 2012-09-19 00:23 UTC
Labels: Bug
