### ISSUE TITLE
Mailing Status Commads not working

### ISSUE THREAD

**Issue by armitage** [soonick/poMMo#7] opened 2010-10-07 10:17 UTC
The commands on "mailing_status.php" (cancel | restart) appear to be working (i.e. no error reported) but have NO effect.

cheers
armitage

**Comment by soonick** [comment] 2010-10-08 00:23
Thank you for reporting this bug. I will try to fix it as soon as I can.

**Comment by dmemarian** [comment] 2011-01-09 16:28
Hi, 

Until there is a fix, do you know what the best way to resolve the issue is? Is there an external script/command that will fix it or does there have to be a complete uninstall and re-install of pommo? I've terminated the current mailing and loaded a completely new one but still get the same error (can't resume the mailing and it's automatically stopped). 

Thanks!

**Comment by soonick** [comment] 2011-01-09 20:42
Right now I dont have any solution to the problem. I am sorry.

**Comment by MDeguelle** [comment] 2011-02-09 08:20
This has to do with a slight bug in the Pommo_Mailing class
In the get method from this class, you construct a query - this query currently misses the fields from the current_mailing table (you can fix this by adding c.\* as a field in the query, just like the original pommo does). 

This means that whenever you get a mailing, like for instance: when polling, trying to respawn during sending or when trying to cancel a sending, the securityCode for the mailing is NOT retrieved from the database and all actions concerning the mailing are ignored.

This also means you can't send mailings past the first batch or the first timeout with pommo as it currently is.
So, to fix: in Pommo_mailing::get; at line 235 add "c.*," (without quotes).

**Comment by soonick** [comment] 2011-02-10 02:32
Thank you for your help MDeguelle. I will add your fix.

**Comment by soonick** [comment] 2011-03-02 03:15
Mailing status commands work again. Thanks to MDeguelle for the fix. Closed by 72a07a0f94542719dc599543b40a1589ee4bbe7a

**Closed as completed by soonick** 2011-03-02 03:15 UTC
Labels: Bug
