### ISSUE TITLE
Importing emails

### ISSUE THREAD

**Issue by adrianloaded** [soonick/poMMo#16] opened 2010-11-05 12:59 UTC
Im trying to import 75,000 emails which keep erroring.

**Comment by adrianloaded** [comment] 2010-11-05 13:17
Getting this error, with import and copy and paste...

MySQL Query Failed. SELECT DISTINCT email FROM `pommo_subscribers` WHERE email IN

**Comment by maxnegro** [comment] 2010-11-06 08:28
are you importing from file? single addresses or csv data?

**Comment by soonick** [comment] 2010-11-06 23:20
Thank you for replying max,

Do you think you can take care of this problem?

**Comment by maxnegro** [comment] 2010-11-07 11:08
I can try but at the moment I'm unable to reproduce.

**Comment by maxnegro** [comment] 2010-11-10 11:44
adrian i'm sorry but I'm quite unable to reproduce your issue. are you sure you're using an up-to-date code base? did you have some tables left from a previous installation of pommo? 
please give us some feedback.

**Comment by soonick** [comment] 2010-11-11 00:44
I'm going to close this bug since max hasn't been able to reproduce it. If you have more information that will help us troubleshoot it you can open it again.

**Closed as completed** 2010-11-11 08:44 UTC

**Comment by maxnegro** [comment] 2010-11-11 10:41
Just for the record: I was able to import 25k test addresses (generated randomly) before hitting a limit on php execution limit as configured on my test machine (~30 secs). I also tried some "obvious" malformed addresses (empty lines, email containg " and ', and so on). No clue of what may have happened, even if the importing code may enjoy some attention.

**Comment by adrianloaded** [comment] 2010-11-17 14:21
Hi guys, sorry about late reply, think i was trying to import more than the script could handle.
all loaded in now though

**Comment by maxnegro** [comment] 2010-11-17 14:30
Tnx for the reply adrianloaded. I think the import should behave better on large loads of addresses, but for the moment I think we should consider closed this issue. Soonick?

**Comment by soonick** [comment] 2010-11-18 00:46
It sounds like php is timing out. I agree, this issue can be closed.

**Comment by maxnegro** [comment] 2010-11-18 08:24
php timing out is one of the problems I encountered, but none of them is causing the error reported at the beginning of thread.
