### ISSUE TITLE
SMTP Relay Issue

### ISSUE THREAD

**Issue by djxpire** [soonick/poMMo#110] opened 2012-12-17 14:26 UTC
I'm trying to connect to Mandril's SMTP server but could not.

I have disabled demo mode,  supplied the correct username password credentials, however within the SMTP relay settings, it simply says: Unable to connect to SMTP server  and using the test relay server is also failed.

How I can solve this? Thank you.

**Comment by soonick** [comment] 2012-12-18 04:40
Hello djxpire,

Does your apache log give any clues of what the error might be?

Regards,
Adrian

**Comment by dineufeld** [comment] 2012-12-22 22:00
I have the same problem. 

Have tried with to connect to Gmail SMTP and to my own SMTP server. 

Regards

**Comment by Ajaz54** [comment] 2012-12-25 00:24
I have the similar issue, I have tried setting Gmail and my SMTP sever but mail did not go through, Although I get the SMTP connection green when I set it to my SMTP Server.

My other options sendmail and PHP Mail Function are also not working. No mails being sent.

Will highly appreciate any help to resolve these issues.

**Comment by soonick** [comment] 2012-12-25 22:07
Hello,

I will investigate into this and let you know if I find something.

**Comment by soonick** [comment] 2012-12-25 22:24
I didn't have any problem connecting to gmail via SMTP. This is the configuration I used. Can you please check if you still have the problem?

![smtp](https://f.cloud.github.com/assets/281836/30644/aa00d674-4ee1-11e2-8505-33b392b7e673.png)

**Comment by soonick** [comment] 2013-01-08 03:47
Closing since unable to reproduce

**Closed as completed by soonick** 2013-01-08 03:47 UTC
Labels: Bug

**Comment by Amrouche** [comment] 2013-02-28 21:19
Hello,

I'm having the same issue here, the connection is ok, however, clicking on "Test Exchanger" I get this error "Error Sending Mai", please advice.

Kind regards,

**Comment by soonick** [comment] 2013-03-02 05:16
Do yo have any information on your server logs?

**Comment by abynur** [comment] 2013-09-23 09:48
hi..sorry to interrupt here..but me also had this problem..after several install/uninstall with many version of pommo..I got this problem..whenever I tried to update smtp this error will happen...
![error](https://f.cloud.github.com/assets/5517695/1190442/33bebdda-2435-11e3-8ee6-838797d1849d.png)
everything will be blank...then i tried to sent test email also will be blank..please help me..tq

**Comment by soonick** [comment] 2013-09-24 04:05
Hello @abynur,

This issue has already been closed. Can you please open a new ticket with your issue?

Thanks,
Adrian
