### ISSUE TITLE
umlauts ä,ö,ü - csv export problem

### ISSUE THREAD

**Issue by pommoficious** [soonick/poMMo#70] opened 2012-05-03 01:03 UTC
hello there,

pommo is really great!! love it..
have just one little problem, does anybody maybe know how to fix that?

exporting umlauts to csv ä,ö,ü doesnt work properly, import instead is no problem...
it generates wrong code...
example: in the csv file it creates ö=√∂ , ä=√§, ü=√º
can someone please help?

thank you very much
sincerely
tom

**Comment by soonick** [comment] 2012-05-03 03:06
Thanks for reporting this issue. We will try to get to it as soon as possible.

**Comment by soonick** [comment] 2012-07-29 18:16
Hello pommoficious,

Can you give me the steps to reproduce this issue? I tried it, but it exported correctly for me.

Regards,
Adrian

**Comment by soonick** [comment] 2012-09-02 22:50
Closing since I wasn't unable to reproduce. Please feel free to reopen if you think the issue is still there.

**Closed as completed by soonick** 2012-09-02 22:50 UTC
Labels: Bug
