### ISSUE TITLE
pommo still freezing

### ISSUE THREAD

**Issue by gdurham** [soonick/poMMo#32] opened 2011-03-05 20:49 UTC
I am still having freezing issues

Started Mailing #2
12:45:31 > Started Mailing MTA. Spawn #1.
10:21:27 > Started Mailing MTA. Spawn #165.

etc

**Comment by soonick** [comment] 2011-05-14 03:27
I am going to close it because I am not able to reproduce it. If you find a way to recreate it please reopen the ticket.

**Closed as completed by soonick** 2011-05-14 03:27 UTC
