### ISSUE TITLE
New install on Windows

### ISSUE THREAD

**Issue by mikekelly1** [soonick/poMMo#52] opened 2011-09-12 07:37 UTC
I installed locally from the main branch onto a xampp setup on a windows system. I created a virtual host and installed pommo in isolation in the root. 
Navigating to the local addressed brought up the login page as though I had already completed the installation. No tables had been created in the local, dedicated, mySQL database at this stage.
I worked around this by commenting out 154 from pommo::init i.e.

self::$_hasConfigFile = true; 

This allowed me to set up the database configuration. I then had to go back and re-instate the above line in order to log in as admin.

There was a further issue. I have not raised a separate ticket in case they are related and caused by my environment or setup. This issue was that when I finally logged in, the site had no styling and the logo failed to register. Checking the html source in firebug showed that the path to the css file was escaped, i.e.

link href="\/themes/shared/css/default.admin.css" rel="stylesheet" type="text/css"

I tried to find the relevant template to check this but the path seems to be generated by Smarty.

**Comment by soonick** [comment] 2011-09-16 01:10
Hello Mike,

Thanks for reporting this bug. I will try to fix it and keep you informed through the process.

Regards,
Adrian

**Comment by soonick** [comment] 2011-09-16 01:45
Hello Mike,

I was trying to reproduce your problem but I didn't find it.

I pulled a clean copy from my master branch, pointed my virtual server to the folder in which I downloaded my branch and everything went fine.

Did you download a clean copy of my master branch?
If you were taken to the login page you probably already have a config.php. Start with a clean state and you won't have one.

If the problem persists please let me know the error apache throws.

I will close this ticket for now because this doesn't seem to be a problem with pommo. If you are still not able to install it, please reopen this same ticket.

Regards,
Adrian

**Comment by mikekelly1** [comment] 2011-09-16 09:52
Hi Adrian,

thanks for looking into the problem for me.

I did have a clean install from the main branch, but I created a 
config.php by editing the sample file as directed in the docs/install 
document. This explains why it jumped the login stage.

After your note, I re-installed the files without creating a config.php 
and it allowed me to enter the database details. Unfortunately it still 
will not run because of the strange escaping of the url's and the links 
to the css files etc. I guess I will just have to wait until the Smarty 
stuff gets removed.

Thanks aain

Mike

**Comment by soonick** [comment] 2011-09-16 15:29
Hello Mike,

If you can paste the errors apache is giving you I could probably help you get this running. Anyway I will take a look at creating the config file manually because I haven't tried that.

Regards,
Adrian Ancona

**Comment by mikekelly1** [comment] 2011-09-16 15:50
Hi Adrian,

After I log in I get a normal Server Not Found error - see attached 
screenshot. The url in the browser is like this:

  http://dev.pommo\/admin.php

If I edit it to remove the \ I can go to the admin.php page but as you 
can see from the second screenshot, there is no styling.

Checking out the page source shows that the head links in the page are 
like this :

<scriptsrc="\/themes/shared/js/jq/jquery.js"type="text/javascript">
<scriptsrc="\/themes/shared/js/pommo.js"type="text/javascript">
<scripttype="text/javascript">
<linkhref="\/themes/shared/css/default.admin.css"rel="stylesheet"type="text/css">

I am running this locally on a windows box.

Thanks again

Mike

**Comment by soonick** [comment] 2011-09-19 23:42
Hello Mike,

I added some commits to the master branch, please verify if they solve your problem. If they do please let me know. If the problem changes, let me know what are the new symptoms.

Thanks,
Adrian

**Comment by mikekelly1** [comment] 2011-09-20 06:37
Hi Adrian,

I am delighted to report that your changes have provided a 100% fix. 
Everything works like a charm.

Thanks again for all your efforts.
Rgds
Mike

**Comment by soonick** [comment] 2011-09-20 22:31
I am very glad.

Thanks for reporting this bug.

**Closed as completed by soonick** 2011-09-20 22:31 UTC
Labels: Bug
