### ISSUE TITLE
attachments don't get sent...

### ISSUE THREAD

**Issue by ghost** [soonick/poMMo#51] opened 2011-08-22 17:53 UTC
Hi all,
I realize this exact same issue is in the 'closed' issues section, but I have the exact same behavior:
I can upload an image or text file just fine (they show up in the attachments folder in pommo on the server), but they never get sent. Tried PHP Mailer and SMTP relay - identical outcome.

If you could let me know where and how to look for information to provide, I'd be happy to help debug this.

Thanks,

Martin

**Comment by jamesarbrown** [comment] 2011-08-22 18:20
Hi Martin,

Please advise issue no that has been closed.

Assume you have tried to send a mailshot without attachment and that works?

James

**Comment by ghost** [comment] 2011-08-22 19:34
Hi James,

Thanks for responding so quickly.

The issue was #27. Note that the original poster does not seem to have confirmed his problem went away?
As to the messages, i can send them with or without attachments and they arrive, they just never include any attachment.

Martin

PS: I run poMMo on CentOS 5.6 with Apache 2.2.3 and php 5.1.6

**Comment by jamesarbrown** [comment] 2011-08-23 07:16
Are you using the test mail.. or are you performing a normal mail shot.

I created a group called test, added just myself and use that for testing by sending a mailshot to just that group. The test mailer has some other issues and wondering if this is just another.

James

**Comment by ghost** [comment] 2011-08-23 07:17
Hi James,

I tried both the test send function and a real send.

Martin

**Comment by jamesarbrown** [comment] 2011-08-23 17:39
Hi Martin,

Yes, difficult... mainly as it works for me and others..... I am sure you mean your php is 5.3.6 and not 5.1.6.?

Its bugging me thatn Pommo is managing to get the attachment onto the server, yet neither send methods work that work for others. 

There are some tables that could be worth a check
pommo_attachment_files
pommo_mailings
pommo_mailings_attachments

Beyond that stuggling to see why it can't relocate the file to attach and mail it. (assuming something is not stripping the attachment inbound!)

Sorry.

James

**Comment by ghost** [comment] 2011-08-23 20:54
Hey James,

The php version is indeed 5.1.6 (CentOS being RHEL minus copyrighted material is rather slow when it comes to bumps in version numbers).

pommo_attachment_files does contain references to files while
pommo_mailings_attachments has mappings of mailings <> attachment files.

how could I look at the logs (or enable some debugging) to see why the files never got added to the sent emails?

Martin

PS: I verified permissions on the folders, but that, too, had no effect. (Even tried with recursive 777 on the whole pommo folder).

**Comment by ghost** [comment] 2011-08-23 20:56
And yet another thought: what kind of php modules are being used in pommo? perhaps a comparison of versions could yield some information? E.g. perhaps I do not even have something important installed, or not a high enough version...

**Comment by ghost** [comment] 2011-08-25 11:24
James, one last question: Are you using the 'master' branch or the 'remove smarty' one?

**Comment by jamesarbrown** [comment] 2011-08-25 12:44
Master. Remove smarty is non operational branch being converted

**Comment by soonick** [comment] 2012-04-08 16:55
Nimloth, I am closing this issue since we didn't hear anything else from you and we weren't able to reproduce it. Feel free to reopen it if you have more information.

**Closed as completed by soonick** 2012-04-08 16:55 UTC

**Comment by nimitgajjar** [comment] 2013-11-07 05:44
Hi Soonick,

Can you tell me is PoMMo is supported Attachments now ?

Nimit Gajjar

**Comment by soonick** [comment] 2013-11-07 17:37
Hello @nimitgajjar,

PoMMo supports attachments now.

Regards,
Adrian
