### ISSUE TITLE
unable to open login page

### ISSUE THREAD

**Issue by Gerhardtf** [soonick/poMMo#148] opened 2013-06-25 13:35 UTC
struggling to install pommo this is the error i get below 

 Work Directory ("/public_html/assegaaibosch/cache") not found! Make sure it exists and the webserver can write to it. You can change its location from the config.php file.

here is the code in my config file 

[workDir] ="/public_html/assegaaibosch/cache" Set the "working" directory. poMMo writes files to this directory. By default, it is set to the "cache" directory in the poMMo root. For increased security move this directory to a location not reachable via the web (e.g. /home/brice/work vs. /home/brice/public_html/work) Make sure the webserver can write to this directory!
[hostname] = www.zmail.co.za/assegaaibosch/pommo Set the webhost's server name

**Comment by soonick** [comment] 2013-06-26 05:05
Hello @Gerhardtf,

The error message is pretty explanatory. Is the cache folder writable by the web server?

**Comment by soonick** [comment] 2013-07-02 02:09
I'm closing this ticket for now. Let me know if you still need help.

**Comment by Gerhardtf** [comment] 2013-07-02 09:05
my problem has not gone away, i have had to attend to other month end stuff
in my bussines sorry for that
i will be looking into the uissue again tomorrow- i am not winning at the
momemt- my deadline being friday
i will advise again
thanks

**Comment by Gerhardtf** [comment] 2013-07-02 20:12
yes the cache folder is writable by the web server. i have also compared server settings with a pommo installation that is currently operational, but still seem to struggle. could i mail u the config file?

**Comment by soonick** [comment] 2013-07-05 19:31
Hey,

Does the folder /public_html/assegaaibosch/cache exist? is public_html in your root / ?

**Closed as completed** 2013-07-09 02:43 UTC
Labels: Bug

**Comment by Gerhardtf** [comment] 2013-07-09 08:33
My Apologies for not getting back to you. Our issues have deteriated. To answer your question.....
Does the folder /public_html/assegaaibosch/cache exist? >> Yes, the directories are there

> > is public_html in your root / ? >>Document root of the site zmail.co.za is /home/zmailco/public_html/

Further to this ......the above issue happens on a linux server using  PHP 5.2 server.

I have another installation on a different server that switched over yesterday from PHP 5.3.3. to PHP 5.4.4, where it was operational and did work on 5.3.3 this is what happens now that i try to login on using 5.4.4.

![pommo](https://f.cloud.github.com/assets/4818695/766968/1eb58b70-e872-11e2-8663-b1b19cabd9d7.png)

**Comment by soonick** [comment] 2013-07-10 04:04
Hello @Gerhardtf,

If the root of your server is **/home/zmailco/public_html/**, it means that **/public_html/assegaaibosch/cache** doesn't exist. You probably want it to point to **/home/zmailco/public_html/assegaaibosch/cache**. You probably configured that in config.php

For the other issue, please open a different ticket if the problem persists, although it seams like the problem is that pommo doesn't currently play well with strict standards so you would need to disable them.

**Comment by Gerhardtf** [comment] 2013-07-12 18:54
i have adjusted the config file accordingly and still it will not open login page

what info can i provide for your assistance please.....the link is at http://www.zmail.co.za/assegaaibosch/pommo/

**Comment by Gerhardtf** [comment] 2013-07-12 22:29
please could you re-open this ticket.i need to resolve this as i dont wish to use other bulkmailers

**Comment by soonick** [comment] 2013-07-13 05:59
Hello @Gerhardtf,

What problem are you having now?

**Comment by Gerhardtf** [comment] 2013-07-13 08:32
i have adjusted the config file accordingly and still it will not open login page

what info can i provide for your assistance please.....the link is at http://www.zmail.co.za/assegaaibosch/pommo/

**Comment by Gerhardtf** [comment] 2013-07-13 08:33
indicating the login page cannot be found

**Comment by soonick** [comment] 2013-07-14 06:28
Hello @Gerhardtf,

This doesn't seem to be a problem with pommo. There are a lot of reasons why your server doesn't find pommo and none of them are related to pommo itself. I would greatly recommend you to contact your webmaster or hosting provider to help you with this problem.

**Comment by Gerhardtf** [comment] 2013-07-15 07:33
Please could you advise some of the possible reasons for the server not to find pommo. what are the basic entry level requirements needed and  settings required  to be made for the system to find pommo.

**Comment by soonick** [comment] 2013-07-15 17:35
Hello @Gerhardtf,

I'm sorry, but without access to the server I can't know what is happening. I don't mean to be rude, but installing pommo requires a minimal understanding of how a web server works and I can't teach that to you.

Regards,
Adrian

**Comment by Gerhardtf** [comment] 2013-07-15 21:13
may i send u the login details via your email?

**Comment by soonick** [comment] 2013-07-16 01:08
Hello @Gerhardtf,

I'm sorry, but I can't help you with this.
