### ISSUE TITLE
Fatal error: Cannot access empty property in /pommo/classes/Pommo_Template.php on line 90

### ISSUE THREAD

**Issue by guidobora** [soonick/poMMo#145] opened 2013-06-16 08:47 UTC
Hallo,
I installed poMMo Master 3 days ago and it works well. However when I send a test email with the CSS template, and then I click on "If you are having trouble viewing this email, click here" I have the problem that I described in the title. I checked the file mailings.php and is the right one. In the configuration Public mailings is ON, and the address to which I sent it is in the list of subscribers.

thanks in advance
best

**Comment by soonick** [comment] 2013-06-17 01:50
Hello @guidobora,

I wasn't able to reproduce the issue. Do you know which hash do you have installed?

**Comment by soonick** [comment] 2013-07-02 02:11
I'm closing this issue since I wasn't able to reproduce. Please let me know if you find more information that can help me reproduce it and I'll take a look again.

**Closed as completed by soonick** 2013-07-02 02:11 UTC
